version: 2.1

parameters:
  run-workflow-1:
    type: boolean
    default: false
  run-workflow-2:
    type: boolean
    default: false

jobs:
  my-job1:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-1 :D"
      - run: echo "Bye from workflow-1 :D"
  my-job2:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-2 :D"

workflows:
  workflow-1:
    when: << pipeline.parameters.run-workflow-1 >>
    jobs:
      - my-job1
  workflow-2:
    when: << pipeline.parameters.run-workflow-2 >>
    jobs:
      - my-job2