version: 2.1

jobs:
  my-job1:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-1 :D"
  my-job2:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-2 :D"
  my-job3:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-3 :D"
  my-job4:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-4 :D"

workflows:
  workflow-1:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - my-job1
      - my-job3
  workflow-2:
    when:
      and:
        - equal: [ develop, << pipeline.git.branch >> ]
    jobs:
      - my-job2
      - my-job4