version: 2.1

jobs:
  hello-job:
    filters:
            branches:
              only:
                - master
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  
    steps:
      - checkout
      - run: echo "hello world using Docker auth with env var :D" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job