version: 2.1

jobs:
  my-job1:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-1 :D"
  my-job2:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello from workflow-2 :D"

workflows:
  workflow-1:
    when:
      and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - my-job1
  workflow-2:
    when:
      and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ nightly_build, << pipeline.schedule.name >> ]
    jobs:
      - my-job2